---
openapi: 3.0.0
info:
  title: Recruiting API
  version: 1.0.0
servers:
- url: https://recruiting-api-dev.mindkey.com
tags:
- name: Vacancy List
- name: Vacancy List > Detailed
- name: Vacancy List > Simple
- name: Vacancy List > Simple > Filters
- name: Vacancy Details
- name: Basic
- name: Old
- name: Lookups
- name: Job Agents
- name: Candidates
paths:
  /{recruiting_customer_id}/vacancies/detailed:
    get:
      tags:
      - Basic
      summary: Get All Vacancies - Detailed
      parameters:
      - name: X-MindKey-User-Language
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: en-US
      - name: Origin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: http://localhost:8080
      - name: recruiting_customer_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    options:
      tags:
      - default
      summary: Options
      parameters:
      - name: Access-Control-Request-Method
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: GET
      - name: Access-Control-Request-Headers
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: "x-mindkey-user-language,x-mindkey-user-name,x-mindkey-user-timezone"
      - name: Origin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: https://localhost:8080
      - name: recruiting_customer_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "204":
          description: No Content
          headers:
            Date:
              style: simple
              explode: false
              schema:
                type: string
                example: "Wed, 15 Mar 2023 09:19:15 GMT"
            Connection:
              style: simple
              explode: false
              schema:
                type: string
                example: keep-alive
            Server:
              style: simple
              explode: false
              schema:
                type: string
                example: Kestrel
            Request-Context:
              style: simple
              explode: false
              schema:
                type: string
                example: appId=cid-v1:3a915af9-4520-41f5-82db-5436fdad8fe6
            Expect-CT:
              style: simple
              explode: false
              schema:
                type: string
                example: "max-age=86400, enforce"
            X-Content-Type-Options:
              style: simple
              explode: false
              schema:
                type: string
                example: nosniff
          content:
            text/plain:
              schema:
                type: string
  /{recruiting_customer_id}/vacancies/simple:
    get:
      tags:
      - Basic
      summary: Get All Vacancies - Simple
      parameters:
      - name: X-MindKey-User-Language
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: da-DK
      - name: Origin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: http://localhost:8080
      - name: recruiting_customer_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /{recruiting_customer_id}/vacancies/configuration/list:
    get:
      tags:
      - Vacancy List
      summary: Vacancy List Configuration
      parameters:
      - name: X-MindKey-User-Language
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: da-DK
      - name: Origin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: http://localhost:8080
      - name: recruiting_customer_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /{recruiting_customer_id}/vacancies/Roti-1:
    get:
      tags:
      - Vacancy Details
      summary: Get Vacancy Details - ExcludeAdvertisementText
      parameters:
      - name: X-MindKey-User-Language
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: da-dk
      - name: Origin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: http://localhost:8080
      - name: IncludeAdvertisementText
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: boolean
        example: "false"
      - name: recruiting_customer_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /{recruiting_customer_id}/vacancies/AdvertisementText/Roti-1:
    get:
      tags:
      - Vacancy Details
      summary: Get Vacancy AdvertisementText
      parameters:
      - name: X-MindKey-User-Language
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: da-dk
      - name: Origin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: http://localhost:8080
      - name: recruiting_customer_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /{recruiting_customer_id}/vacancies/configuration/details:
    get:
      tags:
      - Vacancy Details
      summary: Vacancy Details Configuration
      parameters:
      - name: X-MindKey-User-Language
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: da-DK
      - name: Origin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: http://localhost:8080
      - name: recruiting_customer_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /{recruiting_customer_id}/jobAlerts:
    post:
      tags:
      - Old
      summary: CreateJobAlert (Invalid Mail)
      parameters:
      - name: X-MindKey-User-Language
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: da-dk
      - name: recruiting_customer_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: "\"{\\n\\t\\\"email\\\": \\\"thorsten.hans@thinktecture.com\\\",\\n\\t\\\"emailVerification\\\": \\\"thorsten.hans@thinktecture.com2\\\"\\n}\""
      responses:
        "400":
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
      - Old
      summary: DeleteAllJobAlertsByMail
      parameters:
      - name: X-MindKey-User-Language
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: da-dk
      - name: recruiting_customer_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "204":
          description: Successful response
          content:
            application/json: {}
  /{recruiting_customer_id}/jobAlerts/1:
    get:
      tags:
      - Old
      summary: GetJobAlertDetails
      parameters:
      - name: X-MindKey-User-Language
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: da-dk
      - name: Origin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: http://localhost:4200
      - name: recruiting_customer_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
      - Old
      summary: UpdateJobAlertDetails
      parameters:
      - name: X-MindKey-User-Language
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: da-dk
      - name: recruiting_customer_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: "\"{\\n\\t\\n}\""
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
      - Old
      summary: DeleteJobAlertById
      parameters:
      - name: X-MindKey-User-Language
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: da-dk
      - name: recruiting_customer_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "204":
          description: Successful response
          content:
            application/json: {}
  /{recruiting_customer_id}/jobAlerts/link:
    post:
      tags:
      - Old
      summary: GenerateJobAlertLink
      parameters:
      - name: X-MindKey-User-Language
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: da-dk
      - name: recruiting_customer_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: "\"{\\n\\t\\\"email\\\": \\\"thorsten.hans@thinktecture.com\\\"\\n}\""
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /{recruiting_customer_id}/candidates/lookup/mailingtemplates:
    get:
      tags:
      - Lookups
      summary: Mailing Templates
      parameters:
      - name: X-MindKey-User-Language
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: da-DK
      - name: Origin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: http://localhost:8080
      - name: recruiting_customer_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /{recruiting_customer_id}/candidates/lookup:
    get:
      tags:
      - Lookups
      summary: Lookup Data Specific
      parameters:
      - name: X-MindKey-User-Language
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: da-DK
      - name: Origin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: http://localhost:8080
      - name: IncludeCountry
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: boolean
        example: "false"
      - name: IncludeNationality
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: boolean
        example: "true"
      - name: recruiting_customer_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /{recruiting_customer_id}/job-agents/types/JobAgent:
    get:
      tags:
      - Job Agents
      summary: Get Job Agent Type
      parameters:
      - name: X-MindKey-User-Language
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: da-dk
      - name: Origin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: http://localhost:8080
      - name: recruiting_customer_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /{recruiting_customer_id}/job-agents/create/JobAgent:
    post:
      tags:
      - Job Agents
      summary: Create Job Agent
      parameters:
      - name: X-MindKey-User-Language
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: da-dk
      - name: Origin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: http://localhost:8080
      - name: recruiting_customer_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Henrik Skak Pedersen
                email: henriksp@me.com
                keywords: "Service Design, UX, kommunikation, projektledelse, innovation"
                locations:
                - L5
                regions:
                - Sjælland
                fieldsOfWork:
                - Byggekonst
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /{recruiting_customer_id}/job-agents/resend-email/JobAgent:
    post:
      tags:
      - Job Agents
      summary: Resend E-mail
      parameters:
      - name: X-MindKey-User-Language
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: da-dk
      - name: Origin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: http://localhost:8080
      - name: recruiting_customer_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example: henriksp@me.com
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /{recruiting_customer_id}/job-agents/activate/JobAgent:
    post:
      tags:
      - Job Agents
      summary: Activate
      parameters:
      - name: X-MindKey-User-Language
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: da-dk
      - name: Origin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: http://localhost:8080
      - name: recruiting_customer_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example: F38971DF451B125926EED7867AE08BDFD4D4EF18E81AC86AE023544D3C97925E
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /{recruiting_customer_id}/job-agents/emailexists/JobAgent:
    post:
      tags:
      - Job Agents
      summary: Email Exists
      parameters:
      - name: X-MindKey-User-Language
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: da-dk
      - name: Origin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: http://localhost:8080
      - name: recruiting_customer_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example: henriksp@me.com
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /{recruiting_customer_id}/job-agents/JobAgent:
    put:
      tags:
      - Job Agents
      summary: Update Job Agent
      parameters:
      - name: X-MindKey-User-Language
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: da-dk
      - name: Origin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: http://localhost:8080
      - name: recruiting_customer_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                JobAgentId: 4ad410fd-acae-4aa5-bbad-b725442b23eb
                Code: F38971DF451B125926EED7867AE08BDFD4D4EF18E81AC86AE023544D3C97925E
                name: Henrik Skak Pedersen
                email: henriksp@me.com
                keywords: "Service Design, UX, kommunikation, projektledelse, innovation"
                locations:
                - L5
                - L1
                regions:
                - Sjælland
                fieldsOfWork:
                - Byggekonst
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
      - Job Agents
      summary: Get Job Agent
      parameters:
      - name: X-MindKey-User-Language
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: da-dk
      - name: Origin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: http://localhost:8080
      - name: recruiting_customer_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                JobAgentId: 099a99f2-5d07-4937-94c1-7da93861e8d8
                Code: A2B31CDDEE6EC49805F29EE9929A28DFDAF4CB3C9197868CD175979CC70B0B06
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
      - Job Agents
      summary: Delete Job Agent
      parameters:
      - name: X-MindKey-User-Language
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: da-dk
      - name: Origin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: http://localhost:8080
      - name: recruiting_customer_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /{recruiting_customer_id}/job-agents/configuration:
    get:
      tags:
      - Job Agents
      summary: Get Job Agent Configuration
      parameters:
      - name: X-MindKey-User-Language
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: da-dk
      - name: Origin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: http://localhost:8080
      - name: recruiting_customer_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /{recruiting_customer_id}/candidates:
    post:
      tags:
      - Candidates
      summary: Create Candidate Required Fields
      parameters:
      - name: X-MindKey-User-Language
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: da-DK
      - name: X-MindKey-User-Culture
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: da-DK
      - name: X-MindKey-User-Name
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: RecruitingAPI
      - name: Origin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: http://localhost:8080
      - name: recruiting_customer_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/recruiting_customer_id_candidates_body'
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /{recruiting_customer_id}/candidates/types/Standard:
    get:
      tags:
      - Candidates
      summary: Get Candidate Application Type
      parameters:
      - name: X-MindKey-User-Language
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: en-US
      - name: Origin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: http://localhost:8080
      - name: recruiting_customer_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /swagger/v1/swagger.json:
    get:
      tags:
      - default
      summary: Swagger
      parameters:
      - name: X-MindKey-User-Language
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
        example: da-DK
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
components:
  schemas:
    recruiting_customer_id_candidates_body:
      type: object
      properties:
        candidate:
          type: string
          example: "{\n    \"vacancyId\": \"IMPORT1\",\n\t\"email\": \"hsp@mindkey.com\",\n    \"name\": \"Mandatory Test\",\n    \"registrationTime\": \"{{currentDate}}\",\n    \"allowSave\": true,\n    \"previouslyApplied\": false\n}"
